### ISSUE TITLE
PageDomain function sometimes leaves only TLD

### ISSUE THREAD

**Issue by hr3x8** [hrvojesolc/Custom-Titlebar-Text#4]
Browsing to "https://www.namecheap.com" with {PageDomain} variable will substitute "com" instead of "namecheap.com".

**Comment by XJDHDR** [comment]
I just noticed this myself. In my case though, it didn't get cut down to the TLD.

For example, **https://www.standards.govt.nz/** becomes **govt.nz** in my case.

**Comment by hr3x8** [comment]
In your case it is actually a TLD. Both "nz" and "govt.nz" are considered TLDs. Parser just needs to be smart to understand that.

It it seemingly hard to implement something accurate and sustainable.

I came across this project (https://github.com/NiklasGollenstede/get-tld) that does it accurately but depends on ever changing list (https://publicsuffix.org/list/public_suffix_list.dat).

I'm working on trying to get a regex to work with this list, but I'm thinking it will have to be a downloaded copy of the ".dat" list to be parsed by the plugin.

**Comment by XJDHDR** [comment]
If it helps at all, I'm currently using a version of this addon from before you added the add-on preferences with one of my Firefox profiles. In that version, you used this WebExtensions command to get the hostname:
**window.location.hostname**

and I haven't noticed this bug with that version. Must I assume that it is not possible to determine the hostname that way anymore?

**Comment by XJDHDR** [comment]
I just took a closer look at your code and I see that your current method of getting the domain is to grab the whole URL then pass it into your **convertUrlToDomain** function to chop it down to the domain. 

If I may ask, is there something missing from the **window.location.hostname** command that you need to grab the URL instead?

**Comment by hr3x8** [comment]
I've implemented your suggestion above under a different bug, or shall I say enhancement.

The idea of {PageDomain} is to give you the lowest possible non-TLD hostname. For example, www.server1.pub.service.org should return "pub.service.org" and not the full hostname starting with "www".

Suggestion above implemented. Issue remains to be tackled soon. Requirement for it is not to need to enter many KeePass variables based on one domain if not needed.

**Comment by XJDHDR** [comment]
Thank you for putting that suggestion in. Much appreciated!

As for PageDomain, I hope you manage to get it working. I did find this bug for implementing a "get TLD of URL" function in Firefox but it hasn't been implemented yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1315558

I do have another suggestion though. Currently, you are passing **window.location.href** to your **convertUrlToDomain** function. Since you are just trying to extract the Domain from the URL, I would recommend switching to passing **window.location.hostname** to that function. There are two reasons for this:

1. You can simplify your function. Currently, you are using the function to remove the protocol, subdomain, forward slashes, path and everything after that. If you switch to passing the **window.location.hostname** output, everything except the subdomain is already excluded and so you won't need logic to remove those.
2. There is less chance of bugs occurring. I fact, I have spotted three problems with your function's code that won't occur if you pass only the hostname:

- There doesn't appear to be any logic for removing port numbers from the URL. 
- The protocol removal code only deals with HTTP and HTTPS and won't touch any other protocols (eg. FTP).
- If the URL's path, parameters, etc. contains two or more fullstops, your current code will trim the URL down to the text to the left and right of that last fullstop. As an illustration, this URL: (www.example.com/test.page.html) will be shortened by your function to: (page.html). I have encountered this particular problem in two Google search results pages so far. Similarly, if there is one fullstop in the path and suchlike such as in this URL: **http://www.gpc.edu/webpublishing/url.html**, it will be shortened to **edu/webpublishing/url.html** initially then the **return url.split('/')[0];** command will further strip it down to **edu**.

**Comment by hr3x8** [comment]
This add-on is now defunct.
