### ISSUE TITLE
Req: add {ProfileName} to variables

### ISSUE THREAD

**Issue by intellilogic** [hrvojesolc/Custom-Titlebar-Text#9]
I use multiple profiles and I’m dying for an addon that works with Quantum that shows the profile name in the titlebar.

**Comment by hr3x8** [comment]
Hello intellilogic,

I've looked and this is unfortunately not available resource to get via Web Extension API.

However, this does not mean you can show a profile name in the title bar as a static text. Since you work with profiles, you need to install add-ons for each profile as they are completely separate instances of firefox, settings, etc. What this means is that if you add this add-on to two of the profiles you use, you can use custom text setting in profile 1 to say "djjz8smd - {PageTitle}" and another profile say "mmx7asnro - {PageTitle}". In summary, you can display the profile name manually by providing different custom text.

If you look at Mozilla's page about profiles, add-ons that are mentioned do not work on Quantum (I use it myself): https://developer.mozilla.org/en-US/Firefox/Multiple_profiles.

Hope this helps. I'll keep this as enhancement request with wontfix flag until Mozilla implements profile manipulation in their new API.

Thanks,

Hrvoje

**Comment by intellilogic** [comment]
Ugh, yea, I'm considering doing that, coping the files and then doing a grep to change the var per profile to it's name.  Let me know if it becomes available via the API.

My profiles have names!

`var profiles=[
    'Personal',
    'Email & Business',
    'Dev Research',
    'Linux Research',
    'Shopping',
    'Bus Procurement',
    'IT & Cloud',
    'Music & Ent',
    'Gaming',
    'Home Projects',
    'Veteran issues',
    'Job search',
    'Health',
    'dev-edition-default'
];`
